[workspace]
exclude = ["vendor/vte"]

members = [
    "crates/alacritty",
    "crates/terminal",
    "crates/session",
    "crates/renderer",
    "crates/config",
    "crates/config-derive",
]
default-members = ["crates/alacritty"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.99.0"

[workspace.lints.rust]
rust_2018_idioms = "warn"
future_incompatible = "warn"

[workspace.lints.clippy]
all = "deny"
if_not_else = "deny"
enum_glob_use = "deny"

[profile.release]
lto = "thin"
debug = 1
incremental = false

[workspace.dependencies]
alacritty_terminal = { path = "crates/terminal", version = "0.26.1-dev", default-features = false }
alacritty_session = { path = "crates/session", version = "0.1.0" }
alacritty_renderer = { path = "crates/renderer", version = "0.1.0", default-features = false }
alacritty_config = { path = "crates/config", version = "0.2.4-dev" }
alacritty_config_derive = { path = "crates/config-derive", version = "0.2.6-dev" }
serde = "1"
log = "0.4"
bitflags = "2.4.1"
parking_lot = "0.12.0"
polling = "3.11.0"
crossfont = "0.8.1"
unicode-width = "0.2.0"
toml = "0.9.11"
toml_edit = "0.24.0"

# TODO: Validation of fix for #6978. Remove before next release and use released `x11-clipboard`.
[patch.crates-io]
vte = { path = "vendor/vte" }
x11-clipboard = { git = "https://github.com/quininer/x11-clipboard.git", rev = "19ab2163cf0bd0db607e827a5214571990307866" }
