# Converted from Ghostty's "Atom One Light" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Atom%20One%20Light

[colors.primary]
background = "#f9f9f9"
foreground = "#2a2c33"

[colors.cursor]
background = "#bbbbbb"
foreground = "#ffffff"

[colors.selection]
background = "#d0dffc"
foreground = "#2a2c33"

[colors.normal]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#950095"
cyan = "#3f953a"
white = "#bbbbbb"

[colors.bright]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#a00095"
cyan = "#3f953a"
white = "#ffffff"
