# Converted from Ghostty's "Ayu" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Ayu

[colors.primary]
background = "#0b0e14"
foreground = "#bfbdb6"

[colors.cursor]
background = "#e6b450"
foreground = "#0b0e14"

[colors.selection]
background = "#409fff"
foreground = "#0b0e14"

[colors.normal]
black = "#11151c"
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"
blue = "#53bdfa"
magenta = "#cda1fa"
cyan = "#90e1c6"
white = "#c7c7c7"

[colors.bright]
black = "#686868"
red = "#f07178"
green = "#aad94c"
yellow = "#ffb454"
blue = "#59c2ff"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#ffffff"
