# Converted from Ghostty's "Flexoki Dark" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Flexoki%20Dark

[colors.primary]
background = "#100f0f"
foreground = "#cecdc3"

[colors.cursor]
background = "#cecdc3"
foreground = "#100f0f"

[colors.selection]
background = "#403e3c"
foreground = "#cecdc3"

[colors.normal]
black = "#100f0f"
red = "#d14d41"
green = "#879a39"
yellow = "#d0a215"
blue = "#4385be"
magenta = "#ce5d97"
cyan = "#3aa99f"
white = "#878580"

[colors.bright]
black = "#575653"
red = "#af3029"
green = "#66800b"
yellow = "#ad8301"
blue = "#205ea6"
magenta = "#a02f6f"
cyan = "#24837b"
white = "#cecdc3"
