# Converted from Ghostty's "Horizon" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Horizon

[colors.primary]
background = "#1c1e26"
foreground = "#d5d8da"

[colors.cursor]
background = "#6c6f93"
foreground = "#9fa2c6"

[colors.selection]
background = "#6c6f93"
foreground = "#1c1e26"

[colors.normal]
black = "#000000"
red = "#e95678"
green = "#29d398"
yellow = "#fab795"
blue = "#26bbd9"
magenta = "#ee64ac"
cyan = "#59e1e3"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#ec6a88"
green = "#3fdaa4"
yellow = "#fbc3a7"
blue = "#3fc4de"
magenta = "#f075b5"
cyan = "#6be4e6"
white = "#e5e5e5"
