# Converted from Ghostty's "Jellybeans" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Jellybeans

[colors.primary]
background = "#121212"
foreground = "#dedede"

[colors.cursor]
background = "#ffa560"
foreground = "#ffffff"

[colors.selection]
background = "#474e91"
foreground = "#f4f4f4"

[colors.normal]
black = "#929292"
red = "#e27373"
green = "#94b979"
yellow = "#ffba7b"
blue = "#97bedc"
magenta = "#e1c0fa"
cyan = "#00988e"
white = "#dedede"

[colors.bright]
black = "#bdbdbd"
red = "#ffa1a1"
green = "#bddeab"
yellow = "#ffdca0"
blue = "#b1d8f6"
magenta = "#fbdaff"
cyan = "#1ab2a8"
white = "#ffffff"
