# Converted from Ghostty's "Melange Dark" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Melange%20Dark

[colors.primary]
background = "#292522"
foreground = "#ece1d7"

[colors.cursor]
background = "#ece1d7"
foreground = "#292522"

[colors.selection]
background = "#ece1d7"
foreground = "#403a36"

[colors.normal]
black = "#34302c"
red = "#bd8183"
green = "#78997a"
yellow = "#e49b5d"
blue = "#7f91b2"
magenta = "#b380b0"
cyan = "#7b9695"
white = "#c1a78e"

[colors.bright]
black = "#867462"
red = "#d47766"
green = "#85b695"
yellow = "#ebc06d"
blue = "#a3a9ce"
magenta = "#cf9bc2"
cyan = "#89b3b6"
white = "#ece1d7"
