# Converted from Ghostty's "Monokai Classic" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Monokai%20Classic

[colors.primary]
background = "#272822"
foreground = "#fdfff1"

[colors.cursor]
background = "#c0c1b5"
foreground = "#8d8e82"

[colors.selection]
background = "#57584f"
foreground = "#fdfff1"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#fd971f"
magenta = "#ae81ff"
cyan = "#66d9ef"
white = "#fdfff1"

[colors.bright]
black = "#6e7066"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#fd971f"
magenta = "#ae81ff"
cyan = "#66d9ef"
white = "#fdfff1"
