# Converted from Ghostty's "Nord Light" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Nord%20Light

[colors.primary]
background = "#e5e9f0"
foreground = "#414858"

[colors.cursor]
background = "#7bb3c3"
foreground = "#3b4252"

[colors.selection]
background = "#d8dee9"
foreground = "#4c556a"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#96b17f"
yellow = "#c5a565"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#7bb3c3"
white = "#a5abb6"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#96b17f"
yellow = "#c5a565"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#82afae"
white = "#eceff4"
