# Converted from Ghostty's "Oxocarbon" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Oxocarbon

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.cursor]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "#393939"
foreground = "#626262"

[colors.normal]
black = "#161616"
red = "#00dfdb"
green = "#00b4ff"
yellow = "#ff4297"
blue = "#00c15a"
magenta = "#c693ff"
cyan = "#ff74b8"
white = "#f2f4f8"

[colors.bright]
black = "#585858"
red = "#00dfdb"
green = "#00b4ff"
yellow = "#ff4297"
blue = "#00c15a"
magenta = "#c693ff"
cyan = "#ff74b8"
white = "#f2f4f8"
