# Converted from Ghostty's "Sonokai" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Sonokai

[colors.primary]
background = "#2c2e34"
foreground = "#e2e2e3"

[colors.cursor]
background = "#e2e2e3"
foreground = "#2c2e34"

[colors.selection]
background = "#414550"
foreground = "#e2e2e3"

[colors.normal]
black = "#181819"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"

[colors.bright]
black = "#7f8490"
red = "#fc5d7c"
green = "#9ed072"
yellow = "#e7c664"
blue = "#76cce0"
magenta = "#b39df3"
cyan = "#f39660"
white = "#e2e2e3"
