# Converted from Ghostty's "Vesper" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Vesper

[colors.primary]
background = "#101010"
foreground = "#ffffff"

[colors.cursor]
background = "#acb1ab"
foreground = "#ffffff"

[colors.selection]
background = "#988049"
foreground = "#b9beb8"

[colors.normal]
black = "#101010"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#ea83a5"
white = "#a0a0a0"

[colors.bright]
black = "#7e7e7e"
red = "#ff8080"
green = "#99ffe4"
yellow = "#ffc799"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#f591b2"
white = "#ffffff"
