# Converted from Ghostty's "Zenburn" theme.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/ghostty/Zenburn

[colors.primary]
background = "#3f3f3f"
foreground = "#dcdccc"

[colors.cursor]
background = "#73635a"
foreground = "#000000"

[colors.selection]
background = "#21322f"
foreground = "#c2d87a"

[colors.normal]
black = "#4d4d4d"
red = "#7d5d5d"
green = "#60b48a"
yellow = "#f0dfaf"
blue = "#5d6d7d"
magenta = "#dc8cc3"
cyan = "#8cd0d3"
white = "#dcdccc"

[colors.bright]
black = "#709080"
red = "#dca3a3"
green = "#c3bf9f"
yellow = "#e0cf9f"
blue = "#94bff3"
magenta = "#ec93d3"
cyan = "#93e0e3"
white = "#ffffff"
