name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install pinned Rust toolchain
        run: rustup show
      - name: Workspace tests
        run: cargo test --locked --workspace
      - name: VTE parser
        run: cargo test --locked -p vte
      - name: No default features
        run: cargo test --locked -p alacritty_terminal --no-default-features
      - name: Clippy
        run: |
          cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
  check-macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install target
        run: rustup target add x86_64-apple-darwin
      - name: Build
        run: cargo build --locked --target=x86_64-apple-darwin
